host: '127.0.0.1'
port: 5439

file_managers:
  db: false
  json: true

sys:
  path: '/home/ihebjeridi/Documents/cbliteFinal/couchbase-lite-python'

db_path: '/home/ihebjeridi/Documents/app_OOP/app_acquisation'
db_name: 'AIO_DB'

collections:
  occupants: 'Occupants'
  seats: 'Seats'
  tests: 'Tests'

scope_name: "_default"

seat_data:
  TeslaM:
    SeatName: 'Modular Tesla'
    sensor_numbers_backrest: 4
    SensorNumbersCushion: 6
    CushionWidth: '20 CM'
    FoamMaterial: 'Traditional polyurethane'
    CushionFoamThickness: '20 CM'
    BackrestFoamThickness: '20 CM'
    BolsterCoverMaterial: 'Leather'
    CushionCoverMaterial: 'Leather'
    BackrestCoverMaterial: 'Leather'
  P8:
    SeatName: 'Peugeot'
    sensor_numbers_backrest: 4
    SensorNumbersCushion: 4
    CushionWidth: '12 CM'
    FoamMaterial: 'Auraloop'
    CushionFoamThickness: '12 CM'
    BackrestFoamThickness: '12 CM'
    BolsterCoverMaterial: 'NORMAL'
    CushionCoverMaterial: 'NORMAL'
    BackrestCoverMaterial: 'NORMAL'

